// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Of_phoI0KBkq3QQ7MdaFlUj2nz338QQ',
    appId: '1:629906847377:web:474b779680f63931f03130',
    messagingSenderId: '629906847377',
    projectId: 'testing-hotel-app',
    authDomain: 'testing-hotel-app.firebaseapp.com',
    storageBucket: 'testing-hotel-app.appspot.com',
    measurementId: 'G-KSPKPCBJKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC368V8WCPHdg7vuiGgNmJ7-DgC8sE9eg4',
    appId: '1:629906847377:android:956eb1c09d6a01e3f03130',
    messagingSenderId: '629906847377',
    projectId: 'testing-hotel-app',
    storageBucket: 'testing-hotel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLW3lKFEBkvwlFNJzvS7t_6xVzKKjxjA4',
    appId: '1:629906847377:ios:fd5ac3ed5c089071f03130',
    messagingSenderId: '629906847377',
    projectId: 'testing-hotel-app',
    storageBucket: 'testing-hotel-app.appspot.com',
    iosBundleId: 'com.example.testHotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLW3lKFEBkvwlFNJzvS7t_6xVzKKjxjA4',
    appId: '1:629906847377:ios:c616d63bed75c340f03130',
    messagingSenderId: '629906847377',
    projectId: 'testing-hotel-app',
    storageBucket: 'testing-hotel-app.appspot.com',
    iosBundleId: 'com.example.testHotel.RunnerTests',
  );
}
